use_frameworks!
platform :ios, '8.0'

target 'ZCWView_Example' do
  pod 'ZCWView', :path => '../'

  target 'ZCWView_Tests' do
    inherit! :search_paths

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
